name:                dice
version:             1.1.0.0
github:              "pschnapp/dice"
license:             BSD3
author:              "Paul Schnapp"
maintainer:          "paul.schnapp@gmail.com"
copyright:           "2021 Paul Schnapp"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/pschnapp/dice#readme>

dependencies:
- base >= 4.7 && < 5
- either == 5.0.1.1
- haskeline == 0.7.5.0
- mtl == 2.2.2
- parsec == 3.1.14.0
- random == 1.1
- text == 1.2.4.0
- transformers == 0.5.6.2

library:
  source-dirs: src

executables:
  dice:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - dice

tests:
  dice-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - dice
    - hspec
    - QuickCheck == 2.13.2
